# Site wide configuration

title: Olalekan's github blog
locale: en_US
logo: # filename of a logo image that has been placed into your images directory
theme: jekyll-theme-cayman

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Ganiyu Olalekan
  avatar: bio-photo.jpeg
  bio: "Learner & Reader | Full Stack Web-Developer | Pythonista | AI Enthusiast & Researcher"
  email: ganiyuolalekanmatthew@gmail.com
  # Do not include the @ symbol in your Twitter username
  twitter: GM_Olalekan
  linkedin: ganiyu-olalekan
  github: ganiyuolalekan
  researchgate: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  facebook: ganiyu.olalekan
  instagram: #username
  stackoverflow: 11843596/ganiyu-olalekan
  youtube: #username
  disqus-shortname: go-github.io

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
